# Configuração para rodar no seu computador (Local)
spring.datasource.url=jdbc:postgresql://dpg-d82v84n7f7vs739aibsg-a.virginia-postgres.render.com:5432/clash_db?sslmode=require
spring.datasource.username=clash_db_user
spring.datasource.password=t11q9i80vq1S3TUvM8TGMOW0JOJsBdgw


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

