spring.datasource.url=jdbc:postgresql://dpg-d82v84n7f7vs739aibsg-a:5432/clash_db
spring.datasource.username=clash_db_user
spring.datasource.password=t11q9i80vq1S3TUvM8TGM0W0JOJsBdgw
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method