spring.datasource.url=jdbc:postgresql://dpg-d76osi2a214c739e5om0-a.virginia-postgres.render.com:5432/clashdb_0276?sslmode=require
spring.datasource.username=allan
spring.datasource.password=wTkmhdT6R8PQMqspbdMxqPvZk89HPOIS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true